### ISSUE TITLE
Feature request: add dns01 into template

### ISSUE THREAD

**Issue by dc232** [terraform-iaac/terraform-kubernetes-cert-manager#5]
was wondering if template could be upgrades to support dns1 configs such as 

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  __cloudflareemail__
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - '*.vinsonjewellers.com'
        - vinsonjewellers.com
      dns01:
        cloudflare:
          email: __cloudflareemail__
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: API
```

**Comment by bohdantverdyi** [comment]
Hey, at least you can add your additional cluster issuer. 

Make sure that name of new cluster issuer is not same as in module. 

`resource "kubectl_manifest" "cloudflare_cluster_issuer" {

  validate_schema = false

  yaml_body = <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  __cloudflareemail__
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - '*.vinsonjewellers.com'
        - vinsonjewellers.com
      dns01:
        cloudflare:
          email: __cloudflareemail__
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: API
EOF
  depends_on = [module.cert_manager]
}`

Also good idea to implement support of multiple cluster issuer in module:)

**Comment by timothyclarke** [comment]
In terms of a "second" cluster issuer. It's typically less confusing (and easier to debug) if you keep to 1 cluster issuer but have multiple solvers eg
```
    solvers:
    - dns01:
        route53:
          region: CLUSTER_REGION
          ambient: true
      selector:
        dnsZones:
        - internal.example.com
    - dns01:
        cloudflare:
          email: __cloudflareemail__
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: API
      selector:
        dnsZones:
        - public.example.com
    - http01:
        ingress:
          class: nginx
```
Aka `internal.example.com` is on route53, `public.example.com` is on cloudflare and everything else uses a http01 solver.
